language: python

notifications:
  email: false

python:
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ncbi-blast+ prodigal bowtie2
  
  # diamond
  - wget http://github.com/bbuchfink/diamond/releases/download/v0.8.36/diamond-linux64.tar.gz
  - tar xzf diamond-linux64.tar.gz
  - sudo mv diamond /usr/bin

  # samtools
  - wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2
  - tar jxf samtools-1.9.tar.bz2
  # - pushd samtools-1.9 && ./configure && make && sudo make DESTDIR=/usr/bin install && popd
  - pushd samtools-1.9 && ./configure && make && sudo mv samtools /usr/bin && popd

  # bamtools
  - wget https://github.com/pezmaster31/bamtools/archive/v2.5.1.tar.gz
  - tar xzf v2.5.1.tar.gz
  - pushd bamtools-2.5.1/ && mkdir build && cd build && cmake .. && make && sudo make install && popd

  # bedtools
  # - wget https://github.com/arq5x/bedtools2/archive/v2.28.0.tar.gz
  # - tar xzf v2.28.0.tar.gz
  # - pushd bedtools2-2.28.0 && make && sudo make DESTDIR=/usr/bin install && popd

  # bedtools linux executable
  - wget https://github.com/arq5x/bedtools2/releases/download/v2.28.0/bedtools
  - chmod +x bedtools && sudo mv bedtools /usr/bin

  # bwa
  - git clone https://github.com/lh3/bwa.git
  - pushd bwa && make && sudo mv bwa /usr/bin && popd

  # jellyfish
  - wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.10/jellyfish-linux
  - mv jellyfish-linux jellyfish && chmod +x jellyfish && sudo mv jellyfish /usr/bin
 
install:
  - pip install -r requirements.txt
  - pip install .

script:
  - ./test.sh
