language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ncbi-blast+ prodigal 
  - wget http://github.com/bbuchfink/diamond/releases/download/v0.8.36/diamond-linux64.tar.gz
  - tar xzf diamond-linux64.tar.gz
  - sudo mv diamond /usr/bin

  # samtools
  - wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2
  - tar jxf samtools-1.9.tar.bz2
  - cd samtools-1.9
  - ./configure
  - make
  - make DESTDIR=/usr/bin install

  # bamtools
  - wget https://github.com/pezmaster31/bamtools/archive/v2.5.1.tar.gz
  - tar xzf v2.5.1.tar.gz
  - cd bamtools-2.5.1/
  - mkdir build && cd build
  - cmake ..
  - make
  - make DESTDIR=/usr/bin install

  # bedtools
  - wget https://github.com/arq5x/bedtools2/archive/v2.28.0.tar.gz
  - tar xzf v2.28.0.tar.gz
  - cd bedtools2-2.28.0
  - make
  - make DESTDIR=/usr/bin install

  # bowtie2
  - wget https://github.com/BenLangmead/bowtie2/archive/v2.3.5.1.tar.gz
  - tar xzf v2.3.5.1.tar.gz
  - cd bowtie2-2.3.5.1
  - mkdir build && cd build
  - cmake ..
  - make
  - make DESTDIR=/usr/bin install

  # bwa
  - git clone https://github.com/lh3/bwa.git
  - cd bwa
  - make
  - sudo mv bwa /usr/bin

  # jellyfish
  - wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.10/jellyfish-linux
  - sudo mv jellyfish-linux /usr/bin/jellyfish
 
install:
  - pip install -r requirements.txt
  - pip install .

script:
  - ./test.sh
