language: python

python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ncbi-blast+ prodigal 
  - wget http://github.com/bbuchfink/diamond/releases/download/v0.8.36/diamond-linux64.tar.gz
  - tar xzf diamond-linux64.tar.gz
  - sudo mv diamond /usr/bin
 
install:
  - pip install -r requirements.txt
  - pip install .

script:
  - ./test.sh
