name: rgi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.5
  - pip
  - biopython 1.78
  - filetype >= 1.0.0
  - pytest >= 3.0.0
  - pandas >= 0.15.0
  - matplotlib >= 2.1.2
  - seaborn >= 0.8.1
  - pyfaidx >= 0.5.4.1
  - pyahocorasick 
  - pysam
  - beautifulsoup4 4.9.3
  - requests 2.24.0
  - lxml 4.6.1
  - blast
  - zlib
  - prodigal 2.6.3
  - pyrodigal >=3.0.0
  - diamond 
  - oligoarrayaux 
  - samtools
  - bamtools 
  - bedtools >=2.28.0
  - bowtie2 >=2.3.4.3
  - bwa >=0.7.17
  - kma >=1.2.26s
  - jellyfish
  - dask
